// js/config.js
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121222",
        "on-tertiary-container": "#ffd2be",
        "tertiary-container": "#a44100",
        "outline-variant": "#464555",
        "secondary-container": "#3f407d",
        "on-secondary": "#292965",
        "on-error": "#690005",
        "surface-bright": "#38374a",
        "surface-variant": "#333345",
        "surface-container": "#1e1e2f",
        "on-surface-variant": "#c7c4d8",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary": "#571f00",
        "secondary-fixed-dim": "#c1c1ff",
        "on-primary-container": "#dad7ff",
        "secondary-fixed": "#e1dfff",
        "on-secondary-container": "#afaff4",
        "tertiary": "#ffb695",
        "on-primary-fixed": "#0f0069",
        "primary-container": "#4f46e5",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0c0c1d",
        "inverse-primary": "#4d44e3",
        "surface-container-highest": "#333345",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary": "#1d00a5",
        "on-tertiary-fixed": "#351000",
        "on-secondary-fixed-variant": "#3f407d",
        "secondary": "#c1c1ff",
        "background": "#121222",
        "surface-dim": "#121222",
        "inverse-surface": "#e3e0f8",
        "inverse-on-surface": "#2f2f40",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#ffdbcc",
        "outline": "#918fa1",
        "on-background": "#e3e0f8",
        "surface-tint": "#c3c0ff",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#29283a",
        "primary": "#c3c0ff",
        "on-surface": "#e3e0f8",
        "on-secondary-fixed": "#13124f",
        "primary-fixed": "#e2dfff",
        "surface-container-low": "#1a1a2b",
        "tertiary-fixed-dim": "#ffb695"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1200px",
        "unit": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "code": ["monospace"],
        "body-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "headline-lg": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "code": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
};